- README.rst
- setup.cfg
- src/activator/.dockerignore
- src/activator/.gcloudignore
- src/activator/Dockerfile
- src/activator/activator.py
- src/activator/middleware_interface.py
- src/activator/visit.py
- src/base/Dockerfile
- src/playbook.rst
- src/tester/upload.py
- src/tester/visit.py
- ups/prompt-prototype.table
This PR adds in the code removed from lsst-dm/dmtn-219#2. The code has been cleaned up to pass `flake8`, but no attempt has been made to further reconcile it with LSST conventions such as namespacing.
> DM-33918: Create code repository for prompt processing

- python/activator/activator.py
- python/activator/middleware_interface.py
- python/activator/visit.py
- python/tester/upload.py
- tests/test_middleware_interface.py
This ended up being rather trivial; I'm putting this in review while I keep working on the flask/google.cloud tests (trying to mock a non-installed package (gcloud) is tricky). I'd rather have something to run in a github action now, while we figure out what we want the tests to actually do (I can't mock the butler interface until I have a better sense of how we'll actually use it).
> DM-33935: Create basic test framework for prompt-prototype

- python/activator/Dockerfile
This should enable relative paths to work properly.
> DM-34018: Move activator service one level down.

- doc/playbook.rst
- python/activator/activator.py
- python/activator/middleware_interface.py
- python/tester/upload.py
- tests/test_middleware_interface.py
This PR cleans up the logging to make it more user-friendly.
> DM-33931: Improve logging

- doc/playbook.rst
This PR adds instructions to the Playbook for using the new VM, in particular for working with Google Storage repositories.
> DM-33974: Create a "Butler worker" VM on Google

- bin.src/make_preloaded_export.py
- bin.src/make_remote_butler.py
- doc/playbook.rst
- etc/db_butler.yaml
- python/tester/upload.py
- ups/prompt_prototype.table
This PR provides scripts for distilling `ap_verify_ci_hits2015` into only the data we want to put into the Prompt Processing "initial" repo. Note that `make_remote_butler.py` can only be run on Google Cloud.
> DM-33937: Setup a butler with real data on google cloud

- bin/prompt_prototype_upload_raws.sh
- python/activator/visit.py
- python/tester/upload.py
This PR does a lot of refactoring of `upload.py` to make it easier to edit and more flexible with its inputs, then adds partial support for "observing" preloaded raw files. Because some of the raw metadata is hardcoded into the `get_samples` function, this script will break if any other raws are uploaded to `rubin-prompt-proto-unobserved`.
Because of the heavy refactoring on the first part of the ticket, I recommend reviewing this PR one or a few commits at a time; the net diff combines all the changes into one big rewrite.
> DM-33970: Use real images in upload.py

- doc/playbook.rst
The instructions had gotten out of date with what was needed to actually work with repositories or the APDB.
> Update instructions for creating a Cloud Run service

- python/activator/activator.py
- python/activator/middleware_interface.py
- python/activator/visit.py
- tests/test_middleware_interface.py
This PR adds explicit `instrument` and `skymap` dimensions to all Butler queries, and removes code that the use of default dimensions had made necessary. The result is much more likely to behave consistently in different conditions, increasing the value and relevance of the existing unit tests. The first few commits fix some smaller bugs discovered while examining the code or testing the explicit dimensions.
This PR depends on, and cannot be merged before, #24.
> DM-35941: Remove use of implicit dimensions in Prompt Prototype

- python/activator/activator.py
- python/activator/logger.py
- tests/test_logger.py
This PR fixes several bugs that together prevented some Prompt Processing logs from being correctly parsed by Google Cloud. In the process, it factors out the existing logging setup into a form that will be easier to expand later (e.g., with more context-specific information).
With these changes, the only output that is still unparsed is that from Google infrastructure itself (e.g., worker startup/shutdown) and the "Overriding default configuration file with [path]/config/.dustmapsrc" message, which appears to be sent directly to standard output.
> DM-34020: Get Google Cloud to detect logging levels in prompt_prototype

- Dockerfile.main
- pipelines/calibrate.py
- python/activator/activator.py
- python/activator/middleware_interface.py
- python/tester/upload.py
- tests/test_middleware_interface.py
This PR adds a "merge to central repo" operation to the activator. Because of technical limitations, this operation currently transfers visit-detector level datasets, but not single-ID datasets like task configs or catalog schemas. This limitation will need to be addressed later.
In addition, this PR carries out a large amount of refactoring that was needed to implement and/or debug the primary feature:
- changes to how raws and output datasets are organized into runs, to avoid collisions in the central repo.
- fixes to the construction of `Visit` objects, simplifying code and fixing an untestable type error.
- reorganizing the internal state of `MiddlewareInterface` so that all of it is either a) "persistent" state that is established at class construction, or b) visit-specific state …
> DM-35053: Implement syncing of output products for Prompt Processing

- doc/playbook.rst
This PR updates a number of out-of-date elements of the Playbook:
- Instructions for using `upload.py`
- Instructions for creating and resetting the APDB
- Instructions for creating Butler repos on Google Storage
> DM-36485: Update playbook to give accurate description of upload.py

- doc/playbook.rst
- python/activator/activator.py
- python/activator/logger.py
- python/activator/make_pgpass.py
- python/activator/middleware_interface.py
- python/activator/raw.py
- tests/test_logger.py
- tests/test_middleware_interface.py
- tests/test_raw.py
This PR does a large amount of refactoring centered on `activator.py`, plus some minor reimplementation, with the following goals:
- Removing all LSST dependencies, particularly `Butler` and `Instrument`, from `activator.py`.
- Providing a more platform-independent guarantee that local Butler repos will never collide.
- Separating code within `activator.py` that depends on Google components (Storage and PubSub) from that which does not.
- More unit test coverage of functionality that was previously in `activator.py`, which cannot be imported within the standard `rubin-devl` environment.
- Providing more platform-independent configuration of the databases, especially the APDB.
> DM-36080: Separate GCP-specific code in Prompt Processing prototype

- doc/playbook.rst
I miscounted the optional variables in #27, and some group discussions made it important to clarify that we don't need IP addresses, as such.
> Fix oversights in envvar descriptions

- .github/workflows/build-base.yml
- .github/workflows/build-service.yml
- .github/workflows/lint.yml
All three of our workflows run on Node12 actions, which are being deprecated in favor of Node16. See https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/ for more details.
The lint workflow can be fixed by switching to its reusable counterpart, which is already up to date.
> Update GHA workflows

- doc/playbook.rst
- etc/db_butler.yaml
This PR updates the example Butler config and the Playbook to reflect USDF infrastructure. I've not deleted the Google Cloud equivalents yet, since that is the only platform on which the prototype is operational.
> DM-36509: Set up test Prompt Processing central repository at USDF

- doc/playbook.rst
This is an emergency PR to fix the documentation for working with the central repo; the original examples from #31 gave very bad advice that can wreck users' existing setup.
> Include S3 user profile in bucket examples.

- Dockerfile.main
- doc/playbook.rst
- python/activator/activator.py
- python/activator/logger.py
This PR replaces all Google-specific components (including the logger, which doesn't depend on Google APIs as such) with USDF-appropriate components, and documents how to run the activator on our Kubernetes cluster.
> DM-36712: Migrate activator.py to use Kafka/Knative

- doc/playbook.rst
- python/activator/activator.py
- python/activator/middleware_interface.py
- python/tester/upload.py
- tests/test_middleware_interface.py
This PR contains a number of miscellaneous fixes that prevented an end-to-end run on USDF. Many of these are preexisting bugs that were never exercised on GCP.
> DM-36999: Complete integration test at USDF

- doc/playbook.rst
- python/tester/upload.py
This PR simplifies `upload.py` by removing dummy ("random") file support, and adds an exposure ID injection step to the raw upload process. This change allows the Butler to see each visit/snap as a distinct exposure ID, although it still doesn't allow uploads to be rerun without clearing the APDB first.
> DM-36791: Use unique IDs in upload.py output

- doc/playbook.rst
- python/activator/activator.py
- python/activator/logger.py
- python/tester/upload.py
- tests/test_logger.py
This PR fixes and refactors the logging configuration to better emulate the behavior expected from `pipetask` and BPS. It also adds a log level environment variable, which was requested for debugging our slow run times.
> DM-37258: Logs getting dropped in prompt processing

- python/activator/activator.py
- python/activator/middleware_interface.py
- tests/test_middleware_interface.py
This PR adds code for removing shared (usually init-output) datasets from an output run, making it possible to reuse runs for multiple groups and detectors. Actually implementing reuse is deferred to [DM-36586](https://jira.lsstcorp.org/browse/DM-36586).
The deletion is a stopgap until [DM-36162](https://jira.lsstcorp.org/browse/DM-36162) gives us better tools for handling preexisting or conflicting datasets, so the new code is all written on the assumption that it will be removed later.
> DM-37068: Clear out conflicting datasets before prompt processing runs

- python/activator/middleware_interface.py
- python/tester/utils.py
- tests/test_middleware_interface.py
- tests/test_tester_utils.py
- ups/prompt_prototype.table
This PR adds a regression test for the bug where HSC exposure IDs were being generated with values of 30,000,000+, and rewrites the ID generation algorithm to confine them in the allowed range.
> DM-37547: HSC exposure ID generator produces invalid IDs in 2023

- doc/playbook.rst
This PR adds instructions for using `kubectl describe` to figure out which version of the service a pod is running.
> Document the kubectl describe command in the playbook

- doc/playbook.rst
This PR updates the Playbook with a section of useful tricks for troubleshooting and debugging the prompt processing service.
> Add troubleshooting section to playbook

- bin.src/make_remote_butler.py
- python/tester/upload_hsc_rc2.py
This is a continuation of https://github.com/lsst-dm/prompt_prototype/pull/44 , to fix two bugs there.
> DM-37072: Expand HSC calibs and templates in central repo

- doc/playbook.rst
- python/activator/activator.py
- python/activator/middleware_interface.py
- tests/test_middleware_interface.py
This PR replaces the per-visit raw collection and per-processing output collection with a single raw collection and a per-pipeline output collection, avoiding some scaling and concurrency issues in the central repository. However, the latter change required some reworking of `MiddlewareInterface`, which had assumed that each output collection was new and unique.
> DM-36586: Use a single output run in Prompt Prototype

- python/activator/middleware_interface.py
- tests/test_middleware_interface.py
This PR replaces the old `_query_missing_datasets` with a new function, `_filter_datasets`, that raises if the source repository does not have anything matching the query. This behavior is needed in all contexts where `MiddlewareInterface` queries both the central and local repositories, though it's inappropriate for a general-purpose query.
> DM-37745: Prompt processing preload fails silently if central repo doesn't have prerequisites

- python/activator/activator.py
- python/activator/middleware_interface.py
- tests/test_middleware_interface.py
This PR redesigns `MiddlewareInterface` to be a per-exposure rather than a per-worker object. This change will make it much easier and more foolproof to work with `MiddlewareInterface` in the future, because it no longer needs to avoid storing per-exposure state. This done, the PR replaces `MiddlewareInterface`'s use of `SimplePipelineExecutor` with the `SeparablePipelineExecutor` introduced in lsst/ctrl_mpexec#230.
~The changes to `build-service.yml` and `Dockerfile.activator` are *not* part of the PR, and were temporary hacks to get a service container that had access to `SeparablePipelineExecutor`.~ I intend to wait until lsst/ctrl_mpexec#230 is incorporated into a nightly/weekly before merging this PR; this will allow all actions to complete without hacks.
> DM-36162: Upgrade from SimplePipelineExecutor in prompt prototype

- python/activator/activator.py
- python/activator/middleware_interface.py
- python/tester/upload.py
- python/tester/upload_hsc_rc2.py
- python/tester/utils.py
- tests/test_middleware_interface.py
This PR fixes two bugs in how the output run was defined, one where the run would be timestamped with the pod boot date rather than the processing date, and one where the same processing could try to use different runs. In the course of fixing the latter bug, I've reorganized how `MiddlewareInterface` handles visits and runs; they are now all initialized at `__init__` time, greatly simplifying other methods.
> DM-38752: Output products can go to the wrong collection

- python/activator/middleware_interface.py
- tests/test_middleware_interface.py
This PR changes the naming convention for output runs so that all products of the same pipeline and the same night should go into the same run.
> DM-39395: Use day_obs in run names

- python/activator/activator.py
- python/activator/middleware_interface.py
`MiddlewareInterface.run_pipeline` creates pipeline init-outputs, which can conflict with previous init-outputs if `clean_local_repo` has not been called. Requiring that `clean_local_repo` be called if `run_pipeline` is called prevents the conflict.
An alternative would be to construct the `SeparablePipelineExecutor` with `clobber_output=True`. However, this change may have unintended side effects, especially since the exact behavior of execution flags is subject to change.
> DM-38225: Intermittent init-output collision in Prompt Processing

- tests/test_middleware_interface.py
This PR fixes an API removal (on lsst/daf_butler#841) that was preventing `prompt_prototype` from building.
> DM-39653: Prompt processing unit tests have bitrotted

- python/activator/middleware_interface.py
- tests/test_middleware_interface.py
I hesitate about this because adding a query with the central repo means time spent waiting for the database query, and it probably won't scale well.  If we can agree just don't export raws in all cases, it seems better just to remove it.  Do we really want to wait for [DM-36051](https://jira.lsstcorp.org/browse/DM-36051).?
> DM-39188: Export raws only if they are not already in the central repo

- python/activator/activator.py
- python/activator/config.py
- python/activator/visit.py
- tests/test_config.py
- tests/test_middleware_interface.py
This PR adds some logic that lets us skip Prompt Processing execution for specific types of visits. This is mainly intended for spectroscopic observations taken with LATISS.
> DM-39678: Allow Prompt Prototype to be configured with no pipeline

- .github/workflows/build-service.yml
- pipelines/HSC/ApPipe.yaml
- pipelines/LATISS/ApPipe.yaml
This PR adds an exclusion of the `rbClassify` task from the Prompt Processing pipeline, in case it is added to `ap_pipe` in the future (see comments added in lsst/ap_verify#196 for details on the blockers). This will prevent us from accidentally trying to run the task before we are ready for it.
> DM-40210: Guard against future ap_pipe changes

- python/activator/visit.py
- python/tester/upload.py
- python/tester/upload_hsc_rc2.py
- python/tester/utils.py
- tests/test_config.py
- tests/test_middleware_interface.py
- tests/test_raw.py
- tests/test_tester_utils.py
- tests/test_visit.py
This PR adds a `private_sndStamp` member to `FannedOutVisit`, and modifies the uploaders to populate it based on the exposure time. This is a breaking change to `FannedOutVisit`, and must be merged alongside lsst-dm/next_visit_fan_out#1.
> DM-40296: Add a timestamp to FannedOutVisit

- python/activator/middleware_interface.py
- tests/test_middleware_interface.py
This PR uses `queryDatasetAssociations` to filter out expired calibs during local repo setup. This is not a foolproof solution; in particular, error detection is quite poor because the current code needs to be agnostic to exactly which calibs the pipeline(s) need(s). Error detection will be improved once [DM-40245](https://jira.lsstcorp.org/browse/DM-40245) rewrites calib loading to be more dynamic.
> DM-39514: Add validity-range workaround to prep_butler

- python/activator/activator.py
- python/activator/logger.py
- python/activator/middleware_interface.py
- tests/test_logger.py
- ups/prompt_prototype.table
This PR adds a context manager that allows all logging statements (including those from other packages) to be decorated with metadata about the visit-detector being processed. It also adds a JSON-based log formatter that makes it easier for Grafana queries to take advantage of the extra information.
> DM-35828: Use MDC or equivalent in prompt_prototype logging

- python/tester/upload.py
- python/tester/upload_hsc_rc2.py
This PR reorganizes the raw file upload in `uplaod_hsc_rc2.py` to use a process pool that runs in parallel with the main "exposure-taking" thread. The result is that I/O is no longer a bottleneck for this program; it now runs in the time needed to perform the virtual slew and exposure operations (plus a few seconds for the last visit's upload).
> DM-38215: Parallelize upload_hsc_rc2.py

- bin.src/make_latiss_export.py
A first part of this ticket to get test data into `s3://rubin:rubin-pp-users/central_repo`
> DM-37387: A tester script using LATISS data in /repo/embargo

- python/activator/middleware_interface.py
- tests/test_middleware_interface.py
This PR removes the export/import idiom from MiddlewareInterface. The old idiom needed to use the deprecated `butler.datastore.root` to anchor relative paths, and there's no guarantee that the central repo won't have its datasets split among multiple stores.
> DM-40163: Rework dataset transfer code in MiddlewareInterface

- python/activator/logger.py
- tests/test_logger.py
This PR defers initialization of `RecordFactoryContextAdapter._store.context` to ensure that each thread sees the correct initial state (an empty mapping). This prevents a bug where attempts to log from any thread other than the main one raised an `AttributeError`.
> DM-41084: AttributeError: '_thread._local' object has no attribute 'context'

- python/activator/middleware_interface.py
- tests/test_middleware_interface.py
This PR uses expanded datasetRefs as inputs to all `Butler.transfer_from` calls. This is not strictly required after lsst/daf_butler#895, but it helps minimize the overhead associated with the transfers themselves.
> DM-41165: Prompt processing can't export outputs to /repo/embargo

- python/activator/activator.py
- python/activator/config.py
- tests/test_config.py
This PR makes the pipeline config parsing more flexible regarding survey names, now allowing any character that isn't clearly problematic.
> DM-41658: Prompt Processing can't configure surveys with "-"

- python/activator/middleware_interface.py
- python/activator/visit.py
This is a running PR to test Prompt Processing fixes and the `BASE_TAG_LIST` system. It uses a different branch name from #97 to ensure that `DM-41717-d_2023_11_14` is not overwritten.
> DM-41717: Prompt Processing observing support for AuxTel week 46

- python/activator/activator.py
This PR fixes a logic error in the raw image arrival loop that caused irrelevant images to keep the activator trapped in the loop long after it should have timed out.
> DM-41836: Prompt Processing may wait too long for raws

- python/activator/middleware_interface.py
This PR forces local repos to be created with whatever dimension config the central repo is currently using. This will prevent version mismatches from causing pipeline failures.
The downside of this arrangement is that, when the central repo is upgraded, we will need to make sure to reboot all our pods so that they continue to have a matching local repo. I'm not sure how to ensure that operationally.
> DM-42038: Pipeline execution breaks on dimension version mismatch

- python/activator/logger.py
- tests/test_logger.py
This PR augments `RecordFactoryContextAdapter` to log exceptions with the context in which the exception was raised, not the one in which it was caught.
> DM-41730: Exception logs don't have metadata

- doc/playbook.rst
This PR adds a section to the Playbook for documenting central repo maintenance, including the non-obvious need to reboot our pods when migrating the repo.
> Document repo migration process.

- python/activator/middleware_interface.py
This PR replaces our first call to `queryDatasetAssociations` with a much faster loop over individual datasets. We still need the _second_ call to `queryDatasetAssociations`, which provides the information we need to recertify the calibs we've preloaded (see [DM-41915](https://jira.lsstcorp.org/browse/DM-41915)), but that call will be skipped if calib preload becomes a no-op.
> DM-41713: Many calibs (bias/flat/dark) preloaded in LATISS testing

- python/activator/middleware_interface.py
- python/tester/upload.py
- tests/test_middleware_interface.py
This PR removes the use of `datetime` in `MiddlewareInterface` in favor of `astropy.time`, though some unit tests still use `datetime` as the oracle. It also fixes a bug in our tests that was exposed by lsst/dax_apdb#41.
> DM-42227: Switch from datetime to astropy.time in MiddlewareInterface

- pipelines/HSC/ApPipe.yaml
- tests/data/ApPipe.yaml
Changed `HyperSuprimeCam` to `HSC` and `DarkEnergyCamera` to `DECam` in response to RFC-775.
> DM-33453: Update pipeline references in response to RFC-775.

- doc/playbook.rst
- python/activator/activator.py
- python/activator/middleware_interface.py
- python/activator/timer.py
- tests/test_middleware_interface.py
- tests/test_timer.py
- ups/prompt_processing.table
This PR adds two timing frameworks to Prompt Processing. The first, based on the logger, is flexible and easy to modify, but makes it hard to track long-term changes. The second, based on a hybrid of `lsst.verify` and `analysis_tools`, allows upload of timing metrics to Sasquatch, but individual metrics must be added and removed with care.
> DM-40823: Explore methods for calculating Prompt Processing preload timing

- python/activator/middleware_interface.py
This PR adds extra timing blocks to the calib search path, to try to pin down anomalously slow (tens of seconds) calib queries.
> DM-42809: Add more detailed logging of calib preload

- doc/playbook.rst
This PR cleans up the Playbook to format correctly and conform to the [reST style guide](https://developer.lsst.io/restructuredtext/style.html). The only change of substance is removing a disclaimer that was conditional on DM-36604.
> Formatting fixes to Playbook

- doc/playbook.rst
This PR updates all references to a shared "pp_apdb" namespace in the Playbook. The actual namespaces used by the service are set on lsst-sqre/phalanx#3008.
> DM-42997: Separate APDBs for different instruments in Prompt Processing

- .github/workflows/build-base.yml
- .github/workflows/build-service.yml
- .github/workflows/ci-release.yaml
This PR modifies the Prompt Processing build actions to trigger when the unit tests are updated, to confirm that the new tests pass. It also places the "Release CI" workflow under the same restrictions as "Build and test service", so that it does not trigger on non-code changes.
Unfortunately, since both workflows trigger on changes to the workflow, it's not possible to test these changes on this PR.
> DM-43182: Prompt Processing GitHub Actions don't account for test-only PRs

- python/activator/middleware_interface.py
- tests/test_raw.py
This PR modifies the calib validity hack introduced on #129 to optionally purge the calib cache, preventing conflicts if two calibs are loaded on the same day. While calibs do not change mid-day in production, our integration tests (especially HSC RC2) mix a wide range of "real" observing dates in a single run, and the previous hack would break them.
> DM-43205: Calibs fail to locally certify in Prompt Processing

- .github/workflows/ci-release.yaml
- python/activator/activator.py
This PR changes the `ci-release` workflow to build to `prompt-service` instead of `prompt-processing`. It also turns off PR builds to avoid potentially confusing duplication with `prompt-service`.
> DM-43317: Use prompt-service as sole package for Prompt Processing

- doc/playbook.rst
- python/activator/middleware_interface.py
- tests/test_middleware_interface.py
This PR adds a daily chained collection to the central repo, and refactors some other collection-management code.
> DM-43188: Add a nightly chained collection to Prompt Processing output

- pipelines/LATISS/ApPipe-noForced.yaml
- pipelines/LSSTComCamSim/ApPipe-noForced.yaml
- python/activator/middleware_interface.py
This PR adds a temporary pipeline that turns off forced source loading (and, with future changes to the pipeline, possibly forced source measurement as well). This is a configuration we may need for the Ops Rehearsal, but it is not expected to become the baseline `ApPipe`.
Because the config flag that is set here will not be available until `w_2024_12`, I have not tested the pipeline on our dev cluster. I have, however, confirmed locally that the pipeline definition is valid.
I've also piggybacked a timing improvement that may help us characterize the runtime problems that inspired the `doLoadForcedSources` config in the first place.
> DM-43394: Set up AP pipeline variant that omits forced-source loading

- python/activator/middleware_interface.py
This PR adds a compatibility patch to keep Prompt Processing from crashing when working with version 6 central repositories.
Backwards-compatibility has been verified with unit tests, which emulate a version 4 repo.
> DM-43472: Prompt Processing version 2 not compatible with Butler dimensions-config 6

- python/activator/middleware_interface.py
This PR modifies the code for loading the initial `camera` dataset to get it from `<instrument>/calib` where possible, keeping the old behavior of `<instrument>/calib/unbounded` only as a fallback for older repos.
> DM-43445: Camera load in Prompt Processing assumes a single unbounded collection

- python/activator/activator.py
- python/activator/middleware_interface.py
- tests/test_middleware_interface.py
This PR makes exposure ID determination more robust by sourcing it directly from the ingester.
This PR closes #140.
> DM-43502: Prompt Processing should get expId from ingest, not file path

- python/activator/middleware_interface.py
This PR catches exceptions raised while trying to concurrently modify the central repo's output chain, handling it as something that need not terminate execution. All other registry errors raised during export should still propagate as before.
> DM-43488: Concurrency errors in chain handling interrupt processing

- python/activator/middleware_interface.py
This PR adds an emergency option that turns off dataset caching entirely, for situations where the local repo must not be allowed to grow at all.
Closes #148.
> DM-43584: Add an option to turn off caching entirely

- doc/playbook.rst
This PR fixes an example line in the Playbook to compensate for #137, which makes the Prompt Processing pipelines impossible to run as-is from USDF.
> Add missing config override to register-dataset-types call.

- doc/playbook.rst
This PR improves the release management guidelines in the Playbook in three ways:
- It provides links to look up the latest versions or version histories of dependencies, so that we're aware of what versions are relevant to us (e.g., there is not yet an APDB schema 0.2, but we'd want to know if there is).
- It clarifies how to handle changes internal to Science Pipelines (just writing up what @hsinfang and I have already been doing).
- ~It removes most references to the alert schema version, as I learned from @bsmartradio that this is set dynamically and is not a function of the Science Pipelines release.~ It replaces old language about "alert schema changes" with references to the alert schema versioning policy.
> Update Release Management docs

- python/activator/middleware_interface.py
This PR does some optimization of `Registry.queryDatasets` calls against the central repo, moving data IDs out of `where` clauses and avoiding the use of `...` as a dataset type identifier. `...` is still used to implement the "cache nothing" hack (which is against the relatively small local repo, and needs to pick up _absolutely everything_ to work) and as an explicit argument to `queryDatasetTypes` (where unfiltered queries are the norm).
This PR also uses experience gained with `queryDatasetTypes` to remove the explicit list of refcat dataset types (which was itself a workaround for the impracticality of `...`); since Middleware still doesn't have an explicit "this is a refcat" concept, the new implementation uses a heuristic filter on dimensions and storage class.
> DM-42825: Prompt Processing does slow calib queries against /repo/embargo

- python/activator/middleware_interface.py
- tests/test_middleware_interface.py
This PR replaces all but one of the read-modify-write collection operations in `MiddlewareInterface` with the new atomic methods provided by `daf.butler.ButlerCollections`. This fixes a concurrency bug introduced on #136.
> DM-43316: Use atomic chain operations where appropriate in Prompt Processing

- doc/playbook.rst
- python/activator/middleware_interface.py
- tests/data/ApPipe.yaml
- tests/test_middleware_interface.py
This PR replaces all internal references to `apdb.db_url` with `parameters:apdb_config`, and updates the service configuration interface accordingly. Closes #155.
> DM-44096: Migrate Prompt Processing to external APDB configs

- doc/playbook.rst
Minor version updates to the APDB or Apdb implementations are documented as "backwards compatible", but this is used to mean that new clients can use old databases, not the other way around. This commit adds examples to the versioning guidelines to make it clear that we should not be claiming compatibility with future APDB versions except at the patch level.
> Clarify how minor versions work for APDB.

- pipelines/HSC/Isr.yaml
- pipelines/HSC/SingleFrame.yaml
- python/activator/middleware_interface.py
- tests/test_middleware_interface.py
This PR uses `Apdb.containsVisitDetector` for error handling in pipeline execution, replacing the old dimension packer-based hack.
> DM-44189: Remove ccdVisitId from Prompt Processing

- python/activator/middleware_interface.py
- tests/test_middleware_interface.py
This reverts commit f0c24354b34450ae3d8de16ef201059f6c1679c7 and #160.
> Revert "Migrate from ApdbSql.containsCcdVisit to Apdb.containsVisitDetector."

- python/activator/middleware_interface.py
- tests/test_middleware_interface.py
This PR writes a `RegionTimeInfo` dataset directly to the preload run so that it can be used by preprocessing tasks.
> DM-43948: Create region/time dataset in Prompt Processing

- python/activator/middleware_interface.py
- tests/test_middleware_interface.py
This PR fixes a bug introduced on #158, which broke the mapping between exposure and visit and caused many datasets to effectively "disappear" from the central repo, depending on the query used.
> DM-44393: Prompt Processing does not transfer visit definitions

- python/activator/activator.py
- python/activator/middleware_interface.py
- python/dummyTask.py
- tests/data/MinPrep.yaml
- tests/data/NoPrep.yaml
- tests/data/Preprocess.yaml
- tests/test_middleware_interface.py
This PR adds supporting code that allows a pipeline(s) to be run during `prep_butler`. Without any tasks that can be run on a pre-ingestion repo, however, testing is difficult; many of the changes to the unit tests are workarounds to prevent actual task execution in `prep_butler`.
> DM-42925: Add support for preprocessing pipeline to Prompt Processing

- doc/playbook.rst
This PR adds an alternative way to check an APDB's metadata; it works for both PostgreSQL and Cassandra, but requires bucket credentials.
> DM-42924: Document use of apdb-cli metadata.

- COPYRIGHT
- python/activator/activator.py
- python/activator/caching.py
- python/activator/evictingSet.py
- python/activator/middleware_interface.py
- tests/test_caching.py
- tests/test_evictingSet.py
- tests/test_middleware_interface.py
This PR adds a dataset cache to ensure the local repo never exceeds a configured size. The implementation is quite messy and may need to be replaced later, but the basic configuration hooks should be permanent.
> DM-40193: Disk space leak in prompt processing

- python/tester/upload.py
- python/tester/upload_from_repo.py
This timestamp is used by the fan-out service in lsst-dm/next_visit_fan_out#13, and must be merged first.
> DM-43180: Include private_efdStamp in test messages.

- doc/playbook.rst
- python/tester/upload.py
This PR updates the docs to reflect current conventions for managing APDB configs with both Postgres and Cassandra.
> DM-44844: Deploy Cassandra for production Prompt Processing

- .github/workflows/build-service.yml
- python/activator/activator.py
- python/activator/middleware_interface.py
- tests/test_middleware_interface.py
This PR adds a startup check that removes any prior local repos (from a killed worker) that may be taking up space. This prevents worker failures from cascading to later requests.
If the local repo cannot be removed, the preferred solution is to abort startup entirely; killing and replacing the pod is slow, but guarantees a clean slate.
> DM-43648: Old repos left behind on Prompt Processing worker reboot

- .github/workflows/build-service.yml
This PR fixes invalid shell syntax in `build-service.yml`. It's not clear why the action ran successfully instead of erroring out.
> DM-45084: Quick-container fix breaks tagging of regular Prompt Processing containers

- Dockerfile
This PR adds an optional `WORKER_RESTART_FREQ` variable that restarts the worker after the specified number of requests. If the variable is undefined, it will never restart, as before.
> DM-45007: Memory leak in Prompt Processing service

- doc/playbook.rst
PP does not interact with the "replica" schema, and so is neither compatible nor incompatible with any particular version.
> Clarify that we can ignore ApdbCassandraReplica version.

- Dockerfile
- python/activator/activator.py
- python/activator/exception.py
- python/activator/middleware_interface.py
- tests/test_exception.py
This PR adds configurable timeouts and grace periods to the service container, as well as a handler for TERM signals sent by Knative.
Closes #91.
> DM-40434: Prompt Processing continues processing after timeout or termination

- .github/workflows/build-base.yml
- .github/workflows/build-service.yml
- tests/test_raw.py
- tests/test_tester_utils.py
This PR updates our build system to support rubin-env 9 Pipelines containers. It is backwards-compatible with rubin-env 8.
> DM-45447: Update Prompt Processing base build for rubin-env 9

- .github/workflows/build-base.yml
- .github/workflows/build-service.yml
- .github/workflows/ci-release.yaml
This PR splits the Release CI workflow into separate test and build jobs. The previous, monolithic, job was running out of disk space.
> DM-45825: Prompt Processing "CI Release" workflow broken

- doc/playbook.rst
This PR updates our policy for Butler versioning and documents how to set registry permissions for the PP service accounts.
> Update playbook docs for Butler management

- pipelines/HSC/ApPipe.yaml
- pipelines/HSC/Preprocessing.yaml
- pipelines/LATISS/ApPipe-noForced.yaml
- pipelines/LATISS/ApPipe.yaml
- pipelines/LATISS/Preprocessing-noForced.yaml
- pipelines/LATISS/Preprocessing.yaml
- pipelines/LSSTComCamSim/ApPipe-noForced.yaml
- pipelines/LSSTComCamSim/ApPipe.yaml
- pipelines/LSSTComCamSim/Preprocessing-noForced.yaml
- pipelines/LSSTComCamSim/Preprocessing.yaml
- python/activator/activator.py
- python/activator/middleware_interface.py
This PR splits the pipeline files into separate pipelines, corresponding to the `prompt` and `preload` subsets from lsst/ap_pipe#191.
This pipeline needs to be tested after a daily is built with lsst/ap_pipe#191.
> DM-43418: Divide AP pipeline into preload and prompt subsets

- doc/playbook.rst
This PR gives the correct command to check table permissions in `psql` (`\dp`, not `\dq`).
> Fix bad psql example in Playbook

- doc/playbook.rst
This PR changes the expected registry permissions to be more minimalist; we only need delete permission for a handful of tables, and usage permission for a single sequence. Requesting only the permissions that we truly need should minimize friction with the DBAs as we move into Simonyi commissioning.
> Update Playbook docs for Butler registry permissions

- doc/playbook.rst
This PR updates the procedure for registering dataset types to correct for the pipeline changes in #191.
> Update instructions for registering new dataset types.

- .dockerignore
- .github/workflows/build-service.yml
- Dockerfile
- config/gunicorn.conf.py
- doc/playbook.rst
- python/activator/activator.py
- python/activator/exception.py
- python/activator/repo_tracker.py
- tests/test_repo_tracker.py
This PR refactors the activator to be importable without side effects, as well as to separate application logic from Flask and HTTP-specific logic (this may make it possible to abandon Flask, or to provide alternatives, in the future). It then adds a more sophisticated system for local repo management that allows multiple repos to coexist on the same pod, as well as a configuration flag to request multiple workers from Gunicorn.
> DM-45199: Support multiple workers per Prompt Processing pod

- python/activator/middleware_interface.py
This PR adds behavior flags to `SingleQuantumExecutor` to be less tolerant of pipeline failures.
> DM-46520: Raise on AnnotatedPartialOutputsError in Prompt Processing

- python/tester/utils.py
- tests/test_tester_utils.py
This PR redefines the algorithm for generating mock HSC visit IDs so that we can keep running HSC tests into 2025.
> DM-46603: Reset expired visit ID calculation for Prompt Processing HSC tests

- pipelines/LATISS/ApPipe.yaml
- pipelines/LSSTComCam/ApPipe.yaml
- pipelines/LSSTComCamSim/ApPipe.yaml
This PR adds an explanation for why we only set `doProduceAlerts` in PP, and moves alert generation into the main `ap_pipe` (lsst/ap_pipe#205).
> DM-47067: Document config overrides in PP pipelines

- python/activator/middleware_interface.py
- python/activator/visit.py
- tests/test_middleware_interface.py
This PR adds some special-case handling for nextVisit messages with empty filters (as is common for engineering data). The cases are handled at a fairly low level (`_export_calibs` and `_export_skymap_and_templates`) because I don't see an obvious way to unify what's essentially a query tweak. This may need to be revisited on #204, which reworks how the preload queries are executed.
> DM-47387: Prompt Processing can't handle blank filters in nextVisit message

- python/activator/activator.py
- python/activator/exception.py
This PR fixes an issue where ignorable nextVisit messages (which are normal and expected) were being logged as errors, distracting from actual system failures.
> DM-47388: Prompt Processing logs an error on surveys configured to "ignore"

- python/activator/middleware_interface.py
This PR fixes a logging issue where multi-exposure visits would claim they failed to upload all outputs when they had successfully done so.
> DM-47426: False alarms in Prompt Processing upload

- doc/playbook.rst
Doc update -- I'll self-merge.
> DM-46641: Test new LATISS calibs of IsrTaskLSST in PP dev butler repo

- python/activator/middleware_interface.py
This PR fixes a bug where failure to build a quantum graph because of missing refcats is not handled by falling back to a pipeline that doesn't need them, instead causing execution to abort.
> DM-47628: Prompt Processing does not fall back on missing PrerequisiteInputs

- python/activator/exception.py
- python/activator/middleware_interface.py
This PR improves the error handling around pipeline execution, distinguishing PP execution failures from pipeline failures and ignoring the latter for preprocessing pipelines.
> DM-47591: Allow main pipeline execution if preprocessing pipeline fails

- pipelines/LSSTComCam/SingleFrame.yaml
My understanding of why I was instructed to make these changes in the particular structure I did:
As-is, SingleFrame.yaml exists in prompt_processing but nowhere else. We want a system in which ap_pipe (and ci_pipe and drp_pipe) sit on top of everything else and describe pipeline functionality via yamls. All prompt_processing pipeline yamls should reference and modify counterparts in ap_pipe. At the moment, SingleFrame.yaml is a standalone prompt_processing pipeline, so in addition to adding single-frame association to it, I was asked to also move it into ap_pipe in a traditional LSSTComCam -> _ingredients reference chain.
> DM-47620 Add single-frame SS association to SingleFrame.yaml

- python/activator/middleware_interface.py
- tests/test_middleware_interface.py
This PR fixes an error message that appears when the `nextVisit` message has a position but the service is not configured with any pipelines that use templates.
> DM-47772: Error when preloading for pipelines that don't use templates

- python/activator/activator.py
This PR fixes a bug where the service would ignore (and fruitlessly listen for) already-arrived exposures in multi-snap visits.
> DM-47779: "Existing raws" check ignores multiple snaps

- python/activator/activator.py
- python/activator/config.py
- tests/test_config.py
- tests/test_middleware_interface.py
This PR replaces the bespoke pipelines config format with an extensible YAML-based format, and modifies the config semantics to behave like a prioritized list instead of a mapping. These changes will make it much easier to add new kinds of constraints to the format in the future.
> DM-47529: Migrate Prompt Processing PipelinesConfig to YAML

- python/activator/activator.py
- python/activator/middleware_interface.py
This PR adds a debugging flag that turns `MiddlewareInterface.export_outputs` into a no-op.
> DM-47814: Allow turning off central repo export in Prompt Processing

- python/activator/middleware_interface.py
- tests/test_middleware_interface.py
This PR fixes a bug that flags failed engineering runs as "potentially modifying" the APDB.
> DM-47829: Prompt Processing never retries if exposure does not generate visits

- pipelines/LSSTComCam/ApPipe.yaml
- pipelines/LSSTComCam/SingleFrame.yaml
This PR should wait until after `prompt-base` has the new `ap_pipe` that contains  https://github.com/lsst/ap_pipe/pull/209
> DM-47750: Disable brighter fatter in AP's ISR 

- pipelines/LSSTComCam/Isr-cal.yaml
- python/activator/activator.py
- python/activator/middleware_interface.py
- tests/test_middleware_interface.py
This PR switches Prompt Processing's behavior on `filters=""` visits from preloading calibs for all filters to not preloading filter-dependent datasets at all. This keeps PP deployments from needing to be configured with much larger caches than they would otherwise need. This PR partially reverts #215, though it still _handles_ blank filters instead of generating an invalid query.
> DM-47868: Remove "any filter" processing mode

- pipelines/HSC/ApPipe.yaml
- pipelines/LATISS/ApPipe.yaml
- pipelines/LSSTComCam/ApPipe.yaml
- pipelines/LSSTComCamSim/ApPipe.yaml
This PR temporarily turns on solar system association for ComCam diaPipe, so that we can test it in production.
> DM-48095: AP pipeline does not do solar system association

- .gitignore
- python/activator/middleware_interface.py
This PR catches and handles exceptions from Sasquatch dispatch, preventing them from failing the run.
> DM-48320: Allow Sasquatch upload failures in Prompt Processing

- python/activator/middleware_interface.py
- tests/test_middleware_interface.py
This PR identifies deployments by package hash by default, not just for local builds, and fixes some bugs that made the package hash less consistent than intended.
> DM-47973: Support Keda in MiddlewareInterface._get_deployment

- COPYRIGHT
- bin.src/make_export.py
- etc/export_comCamSim.yaml
- etc/export_hsc_rc2.yaml
- etc/export_latiss.yaml
- python/activator/middleware_interface.py
- tests/test_middleware_interface.py
This PR removes the workarounds added on #129 and #135 and adds new implementations of calib validity queries. It also migrates old-style queries to the current system where an equivalent exists.
> DM-46178: Use new query system in Prompt Processing

- base/Dockerfile
- python/activator/activator.py
- python/activator/visit.py
Converts fan out message unpacking to Redis Streams with support to handle multiple messages per Keda worker.  Removes Kafka support for message unpacking of fanned out visits.  The prompt processing base image is updated with python libraries for Redis and Prometheus.  Prometheus is used to track utilization of running instances vs instances that are processing.
> DM-47975: Handle multiple messages per Keda worker in Prompt Processing

- python/activator/middleware_interface.py
- python/tester/upload.py
This PR fixes some of the logs in `middleware_interface` that were left too ambiguous by the code reorganization in #249.
> DM-48842: Prompt Processing query errors don't report which query failed

- python/activator/activator.py
- python/activator/middleware_interface.py
- python/shared/config.py
- python/shared/raw.py
- python/tester/upload.py
- python/tester/utils.py
This PR does some code cleanup and adds status-sensitive latency logs to Keda. It also fixes a bug where DC2 refcats weren't being given enough cache space.
> DM-49204: Instrument Keda activator with equivalent of Knative's request latency

- python/activator/activator.py
This PR adds periodic worker restarts to Keda. This feature is needed to mitigate memory leaks in Science Pipelines.
> DM-49078: Add support for worker restarts to Keda

- doc/playbook.rst
- python/activator/activator.py
This PR refactors the Redis connection management to something with lower algorithmic complexity, then adds a check to both Knative and Keda that rejects messages sent too long ago.
> DM-49427: Filter out old fanned-out messages in Keda

- python/activator/activator.py
This PR adds correct handling of `GracefulShutdownInterrupt` to Keda. The code is rather clunky, but I don't see a way to simplify it given the need to support retries in the future.
> DM-49477: GracefulShutdownInterrupt does not shut down Keda workers

- .github/workflows/ci-release.yaml
- README.rst
This PR adds a badge to the readme, and fixes the Release CI workflow's trigger conditions to ignore merges to `main` (a job condition prevents these from actually running, but they still count as execution history).
> Add status badge for Release CI workflow

- README.rst
This PR adds a couple of extra badges to the one added in #279, to provide other info useful to developers.
> Expand status badges for Release CI workflow

- python/activator/middleware_interface.py
- tests/data/make_central_repo.sh
This PR adds forward-compatibility with the `template_coadd` dataset type mandated by [RFC-1049](https://rubinobs.atlassian.net/browse/RFC-1049). It keeps compatibility with `deepCoadd`/`goodSeeingCoadd` until those fall out of use.
[RFC-1049]: https://rubinobs.atlassian.net/browse/RFC-1049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DM-49966: Support new-style coadds as Prompt Processing templates

- .dockerignore
- Dockerfile
- config/astropy.cfg
- init-output-run/Dockerfile
This PR adds a (shared) Astropy config file to the init and service pods. The config is not included in the deployment ID calculation.
> DM-50071: IERS download blocked from Prompt Processing pods

- python/activator/middleware_interface.py
- python/shared/raw.py
- tests/test_middleware_interface.py
This PR fixes a bug introduced by #249 that causes filtered calibs to be loaded unconditionally, and improves our tests and code to keep it from happening again.
> DM-50299: Prompt Processing always tries to load filter-dependent calibs

- doc/playbook.rst
This PR updates our release guidelines to support looking up the `ApdbCassandraReplica` version. It also removes the long-irrelevant manual tagging instructions.
> Update release docs for ApdbCassandraReplica

- python/tester/upload.py
This PR fixes an issue in `upload.py` (but not `upload_from_repo.py`) where the nextVisit provided a band when it needed a filter.
> DM-50328: Prompt Processing upload.py sends band instead of physical filter for LATISS

- pipelines/LSSTCam/Isr-cal.yaml
This PR turns off an option that gives the following error: `ValueError: Cannot apply quadratic crosstalk correction with doBootstrap=True.`
> Reconfigure ISR-Cal for latest obs_lsst

- pipelines/LSSTCam/Isr-cal.yaml
This PR partially reverts #298, reactivating bootstrap mode for ISR-cal while keeping crosstalk correction off.
> DM-50423: Optimize ISR-cal for obs_lsst w_2025_16 and later

- doc/playbook.rst
- pipelines/HSC/SingleFrame.yaml
- pipelines/LATISS/SingleFrame.yaml
- pipelines/LSSTCam-imSim/SingleFrame.yaml
- pipelines/LSSTCam/SingleFrame.yaml
- pipelines/LSSTComCam/SingleFrame.yaml
- pipelines/LSSTComCamSim/SingleFrame.yaml
This PR corrects the definition of our `SingleFrame` pipelines to be more aligned with `ap_pipe`'s.
> DM-50500: Prompt Processing uses incorrect definition of `SingleFrame`

- doc/playbook.rst
This PR removes the remaining documentation specific to `prompt-proto-service` or Knative.
> DM-50751: Remove prompt-proto-service references from Playbook

- python/activator/middleware_interface.py
This PR fixes a bug that occasionally causes `_export_calib_associations` to crash.
> DM-51065: Prompt Processing tries to associate calibs it did not preload

- python/tester/utils.py
- tests/test_tester_utils.py
This PR fixes a bug in uploaders' group recognition code that sometimes caused group IDs to be reused, causing PP to import the wrong image.
> DM-51080: Uploaders may duplicate group IDs

- python/activator/middleware_interface.py
- tests/data/ISR.yaml
- tests/test_middleware_interface.py
This PR self-consistently identifies inputs from the set of configured pipelines, though some hard-coding is still needed to handle classes of dataset types that behave differently (calibs, spatial datasets, etc.).
> DM-40245: Intelligently identify datasets to preload

- python/activator/middleware_interface.py
- python/initializer/write_init_outputs.py
- python/shared/connect_utils.py
- tests/test_connect_utils.py
- tests/test_middleware_interface.py
This PR adds delayed retries to the major Butler operations (Butler initialization, preload, and export) to compensate for cases where the repo is overloaded. It also cleans up some vestigial code.
> DM-41738: Make Prompt Processing more robust to Butler connection failures

- python/activator/activator.py
- python/activator/middleware_interface.py
- python/tester/upload.py
- tests/test_middleware_interface.py
This PR compares the sky rotation angles in the nextVisit message and the image header, and rejects the image for processing if they don't match. This prevents rotated visits from being partially processed, depending on the exact HTM/patch coverage involved.
> DM-50617: Abort Prompt Processing if camera rotation different from nextVisit

- base/Dockerfile
This PR replaces mamba with conda and otherwise brings the base container up to date.
> DM-51134: Migrate away from Mamba in Prompt Processing build infrastructure

- python/activator/activator.py
- python/activator/middleware_interface.py
- python/initializer/write_init_outputs.py
This PR adds retries of Butler operations on `InterfaceError` and Redis operations on `ConnectionError`.
> DM-51389: Expand use of retry in Prompt Processing

- python/activator/activator.py
- python/activator/middleware_interface.py
- python/initializer/write_init_outputs.py
- tests/data/make_central_repo.sh
- tests/test_middleware_interface.py
- tests/test_write_init_outputs.py
This PR changes the repo configuration to use a two-tier system, with an optional read-only repo to reduce load on the write repo. It also removes the old "calib repo" terminology.
> DM-51139: Support separate read and write butlers in Prompt Processing

- python/activator/activator.py
- python/activator/middleware_interface.py
- tests/test_middleware_interface.py
This PR fixes a bug where Prompt Processing inadvertently tried to modify a read-only central repo.
> DM-51696: Prompt Processing can't use read-only central repos

- doc/playbook.rst
- python/tester/upload.py
This reverts commit 0b35aa8531df1d0fcac600019b458845d6d25328.
> DM-50223: Refresh LSSTCam tests with newer data, use real angle for LSSTCam tests.

- python/activator/middleware_interface.py
This PR fixes an oversight in #316 that let partially-initialized local repos still break preload.
> DM-51922: Failed preload can still break Prompt Processing local repo

- python/activator/middleware_interface.py
This PR removes the confusing "off by one" aspect of the local dataset cache, and doesn't cache (or check) spatial datasets at all.
> DM-51735: Stop caching spatial datasets in Prompt Processing

- tests/test_connect_utils.py
This PR fixes a bug where a randomized unit test doesn't account for its own overhead.
> DM-52221: Transient ConnectionUtilsTest failure at Jenkins macos 

- python/activator/activator.py
- python/activator/kafka_butler_writer.py
- tests/test_kafka_butler_writer.py
When using the Kafka Butler writer service to transfer outputs to the central repository, we now write files directly to their final location in the Butler datastore.  This avoids wasting S3 bandwidth from the writer service making a copy of the files.
This requires a new `daf_butler` function that is only available starting from the August 29th daily, and release 2.0.1 of the butler writer service.  This new version is not backwards-compatible with the previous 1.0.0 version of the writer service.
> DM-52180: Write files to datastore for Butler writer service

- Dockerfile
This PR modifies the main service's Dockerfile to run Keda natively, without the need for an external override.
> DM-52568: Add Keda run command to main Dockerfile.

- doc/playbook.rst
This PR adds all Prompt Processing's dependencies to the release guidelines. Unfortunately, we don't have a way to check most of these versions yet.
> Update release management guidelines with new dependencies
